require("dashboard").setup({
	theme = "hyper",
	change_to_vcs_root = true,
	config = {
		header = {
			[[                                                                                   ]],
			[[     /\__\         /\  \         /\  \         /\__\          ___        /\__\     ]],
			[[    /::|  |       /::\  \       /::\  \       /:/  /         /\  \      /::|  |    ]],
			[[   /:|:|  |      /:/\:\  \     /:/\:\  \     /:/  /          \:\  \    /:|:|  |    ]],
			[[  /:/|:|  |__   /::\~\:\  \   /:/  \:\  \   /:/__/  ___      /::\__\  /:/|:|__|__  ]],
			[[ /:/ |:| /\__\ /:/\:\ \:\__\ /:/__/ \:\__\  |:|  | /\__\  __/:/\/__/ /:/ |::::\__\ ]],
			[[ \/__|:|/:/  / \:\~\:\ \/__/ \:\  \ /:/  /  |:|  |/:/  / /\/:/  /    \/__/~~/:/  / ]],
			[[     |:/:/  /   \:\ \:\__\    \:\  /:/  /   |:|__/:/  /  \::/__/           /:/  /  ]],
			[[     |::/  /     \:\ \/__/     \:\/:/  /     \::::/__/    \:\__\          /:/  /   ]],
			[[     /:/  /       \:\__\        \::/  /       ~~~~         \/__/         /:/  /    ]],
			[[     \/__/         \/__/         \/__/                                   \/__/     ]],
			[[                                                                                   ]],
			[[                                                                                   ]],
			[[Press <Space> to Start]],
			[[                                                                                   ]],
			[[                                                                                   ]],
			[[                                                                                   ]],
		},
		packages = { enable = true },
		shortcut = {
			{ desc = " Update", group = "@property", action = "Lazy update", key = "u" },
			{
				desc = "  Label",
				icon_hl = "@variable",
				group = "Label",
				action = "Telescope find_files",
				key = "f",
			},
			{
				desc = "  @blinfoldking",
				group = "Number",
				action = [[lua require("link-visitor").visit("https://github.com/blinfoldking")]],
				key = "g",
			},
		},
		project = { enable = false },
		footer = {
			"",
			"",
			"",
			"I have no fear, for fear is the little death that kills me over and over.",
			"Without fear, I die but once.",
			"",
			"",
			"",
		},
	},
})
